### ISSUE TITLE
where is build/render?

### ISSUE THREAD

**Issue by lzh-awesome** [Farama-Foundation/MAgent#12]
![image](https://user-images.githubusercontent.com/67398861/163673895-a6ba33be-a44c-48c3-bade-8c738e702829.png)
i try to run the first demo by command python examples/train_battle.py ,but no No such file or directory: 'build/render'

**Comment by dsctt** [comment]
Hi, if you `mkdir build` first, it should get it to run.

**Comment by lzh-awesome** [comment]
Hi @dsctt ,i check the websit ehttps://github.com/geek-ai/MAgent and run commend bash build.sh in the terminal ,then it generates build/render，thanks a lot！！！
