### ISSUE TITLE
How to watch video using config.json and video_x.txt?

### ISSUE THREAD

**Issue by Chuan-shanjia** [Farama-Foundation/MAgent#16]
Hello,I have trained the model successfully.I got a config.json file and several video_x.txt files in build/render. Could you tell me how to display them?(I see render.py in MAgent folder, but I don't know how to call it. It seems to get information from env instead of video_x.txt and the videos can't be saved). Thank you!

**Comment by BenW3** [comment]
I'm having the same issue. Did you figure this out?

**Comment by BenW3** [comment]
Ok, not sure if anyone is still interested, but there's a helpful pettingzoo tutorial that provides an answer: https://towardsdatascience.com/using-pettingzoo-with-rllib-for-multi-agent-deep-reinforcement-learning-5ff47c677abd. 
You can use the provided renderer in exactly the same way as he does and output a gif.
