### ISSUE TITLE
Instructions on rendering

### ISSUE THREAD

**Issue by joleeson** [Farama-Foundation/MAgent#6]
This issue relates to the 'Get Started' document, subtitle 'Watch Video'.

Instruction to 'execute ./render' is vague. There is no such file in the designated folder destination when an example is run. Could the authors please clarify?

**Comment by benblack769** [comment]
Also note that this is a maintained fork, we are not the original authors of the repo.

**Comment by joleeson** [comment]
ok thank you ben.

**Comment by benblack769** [comment]
@joleeson As a result of your issue, we are planning to move the render code from pettingzoo to this repo. The start of that is in #7 . Just to give you a heads up.
